apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-product
  template:
    metadata:
      labels:
        app: broker-product
    spec:
      enableServiceLinks: false
      containers:
        - name: broker-product
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9093
            - containerPort: 29093
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_ID
                  name: kafka-product-config
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ZOOKEEPER_CONNECT
                  name: kafka-product-config
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                  name: kafka-product-config
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ADVERTISED_LISTENERS
                  name: kafka-product-config
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                  name: kafka-product-config
---
apiVersion: v1
kind: Service
metadata:
  name: broker-product
spec:
  selector:
    app: broker-product
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
      name: kafka-external
    - protocol: TCP
      port: 29093
      targetPort: 29093
      name: kafka-internal
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-product-config
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-product:2182"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-product:29093,PLAINTEXT_HOST://localhost:9093"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"