apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-product
  template:
    metadata:
      labels:
        app: schema-registry-product
    spec:
      enableServiceLinks: false
      containers:
        - name: schema-registry-product
          image: confluentinc/cp-schema-registry:7.5.0
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 'broker-product:29093'
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://schema-registry:8082
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-product
spec:
  selector:
    app: schema-registry-product
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8082
      name: schema-registry