apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-product
  template:
    metadata:
      labels:
        app: zookeeper-product
    spec:
      containers:
        - name: zookeeper-product
          image: confluentinc/cp-zookeeper:7.5.0
          ports:
            - containerPort: 2182
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  key: ZOOKEEPER_CLIENT_PORT
                  name: zookeeper-product-config
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  key: ZOOKEEPER_TICK_TIME
                  name: zookeeper-product-config
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-product
spec:
  selector:
    app: zookeeper-product
  ports:
    - protocol: TCP
      port: 2182
      targetPort: 2182
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-product-config
data:
  ZOOKEEPER_CLIENT_PORT: "2182"
  ZOOKEEPER_TICK_TIME: "2000"