apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  SPRING_DATA_MONGODB_URI: "mongodb://root:password@mongodb.default.svc.cluster.local:27017/product-service?authSource=admin"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.default.svc.cluster.local:9093"
  SPRING_KAFKA_TEMPLATE_DEFAULT_TOPIC: "product-producer"
  LOKI_URL: "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
